name: Pipeline CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Lint
        run: python -m flake8 . --count --exit-zero --statistics

      - name: Test
        run: python -m pytest